### ISSUE TITLE
::Fixnum is deprecated 

### ISSUE THREAD

**Issue by blackwellsmith** [learn-co-curriculum/sinatra-shotgun-server#29] opened 2019-04-08 19:46 UTC
So I can't do the code along.

**Comment by drakeltheryuujin** [comment] 2019-09-24 14:21
Hi there,

I am able to complete this lesson, even with the warning `warning: constant ::Fixnum is deprecated`. I'm unable to reproduce any issues, so I'm going to close it for now.

If you can provide further detail about what is blocking you from completing this lesson, I'd be happy to take a second look!

As always, thanks for contributing! 💙

**Closed as completed by drakeltheryuujin** 2019-09-24 14:21 UTC
